### ISSUE TITLE
crash when looking at log splitter recipe

### ISSUE THREAD

**Issue by kasirii** [FlexibleGames/VintageEngineering#6] opened 2024-07-21 13:17 UTC
some weird mod interactions i guess

Game Version: v1.19.8 (Stable)
21.07.2024 20:05:55: Critical error occurred
Loaded Mods: cattailsfromgrass@0.1.0, chiseltools@1.12.3, crackedrockweak@1.0.0, extrachestsfantasyedition@1.8.0, indappledgroves@0.6.0-dev.2, jackofalltraits@1.0.0, primitivesurvival@3.5.7, qptech@1.15.2, sticksfromplanks@0.1.0, swordz@1.1.8, vichnybackpack@1.0.0, vintageengineering@0.1.4, game@1.19.8, abcsreborn@0.2.2, animationmanagerlib@0.7.2, apewindows@1.0.0, augplantlib@0.0.3, beehivekiln@1.6.1, betteritemflags@0.1.0, betterfirepit@1.1.4, biggercellars@1.0.0, butchering@1.6.1, cancrops@0.1.25, commonlib@2.5.0-rc.2, cooperativecombat@1.1.1, herbarium@1.2.0, immersivewoodsawing@0.2.2, krpgenchantment@0.2.11, levelup@1.2.5-pre.3, minerz@0.1.2, Spear-Expantion-by-Kanahaku@0.1.3, outlawmod@1.2.3, petai@2.2.4, prospecttogether@1.3.0, rivers@3.1.0, sawdebarkedlogs@0.1.0, simplefootstepsredux@1.0.0, somethinginthewater@1.2.4, tieredarrows@1.1.0, trailmod@1.0.8, creative@1.19.8, vsimgui@1.1.5, survival@1.19.8, vsvillage@1.0.5, metalrecovery@0.1.19-pre.1, configlib@1.3.13, extraoverlays@1.4.0, feverstonewilds@1.5.0-rc.2, fsmlib@0.4.1, gardenerz@0.1.1, newworldcrops@0.0.7, simplevillages@1.0.1, stonequarry@3.3.1, vsvillagedesert@1.0.0, vsvillageaged@0.0.1, wildcraftfruit@1.2.1, maltiezcrossbows@0.3.11, maltiezfirearms@0.5.4
System.ArgumentException: Attempted to resolve the recipe ingredient wildcard Item game:axehead-* but there are no such items/blocks!
   at Vintagestory.API.Client.SlideshowGridRecipeTextComponent..ctor(ICoreClientAPI capi, GridRecipe[] gridrecipes, Double size, EnumFloat floatType, Action`1 onStackClicked, ItemStack[] allStacks) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\SlideshowGridRecipeTextComponent.cs:line 102
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.addCreatedByInfo(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor, ItemStack stack, List`1 components, Single marginTop, Boolean haveText) in VSSurvivalMod\Systems\Handbook\CollectibleBehaviorHandbookTextAndExtraInfo.cs:line 1137
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.GetHandbookInfo_Patch1(CollectibleBehaviorHandbookTextAndExtraInfo this, ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.GameContent.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 117
   at Vintagestory.GameContent.GuiHandbookItemStackPage.ComposePage(GuiComposer detailViewGui, ElementBounds textBounds, ItemStack[] allstacks, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 113
   at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 283
   at Vintagestory.GameContent.GuiElementFlatList.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VSSurvivalMod\Systems\Handbook\Gui\GuiElementFlatList.cs:line 93
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 449
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 584
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 412
   at Vintagestory.Client.NoObf.ClientMain.UpdateMouseButtonState(EnumMouseButton button, Boolean down) in VintagestoryLib\Client\ClientMain.cs:line 1919
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack, Boolean keyup) in VintagestoryLib\Client\HotkeyManager.cs:line 431
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUpRaw(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1934
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 208
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)

**Comment by kasirii** [comment] 2024-07-21 15:20
probably "in dappled groves" removed the vanilla axe.

**Comment by FlexibleGames** [comment] 2024-07-23 21:46
That's what I get for assuming an ingredient exists!

**Comment by FlexibleGames** [comment] 2024-07-23 22:06
So @kasirii  I'm assuming the machine is not craftable at all.

**Comment by FlexibleGames** [comment] 2024-08-07 04:16
Closing as it is not a bug with my mod. Contact the author of the other mod to create a quick JSON patch to edit the velogsplitter grid recipe.

**Comment by FlexibleGames** [comment] 2024-08-07 04:18
Close #6

**Comment by FlexibleGames** [comment] 2024-08-07 04:19
closed

**Closed** 2024-08-07 04:20 UTC
Labels: bug
